name: dotnet package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rid: ['win-x64', 'linux-x64', 'osx-x64']

    steps:
      - name: Variables
        id: vars
        run: echo sha_short=${GITHUB_SHA::7} >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET Core SDK 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish --sc false -r ${{ matrix.rid }} -c release -o ${{ matrix.rid }} -p:PublishSingleFile=true
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.vars.outputs.sha_short }}-${{ matrix.rid }}
          path: ${{ matrix.rid }}

  release:

    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - name: Variables
        id: vars
        run: echo sha_short=${GITHUB_SHA::7} >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: for a in *; do zip -r "$a.zip" "$a"; done
        working-directory: artifacts
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            artifacts/*.zip
